theme: jekyll-theme-cayman
title: "Gaussian Process Priors for View-Aware Inference"
description: "<a href='#'>Yuxin Hou</a>, <a href='#'>Ari Heljakka</a>, and <a href='http://arno.solin.fi'>Arno Solin</a>"
arxiv: "#"
markdown: kramdown
